src/Fixie/Execution/ExecutionEnvironment.cs
Today if a listener don't inherit from MarshalByRefObject you get the following error
````
System.Runtime.Serialization.SerializationException: Type '{YourListener}' in Assembly '{YourAssembly}' is not marked as serializable.
````
While it does give you a hint about what is wrong the change in this PR clearly states what's wrong.
=> added guard against invalid listener type hierarchies

src/Fixie.TestDriven/TdNetRunner.cs, src/Fixie/Internal/Runner.cs
When using the TestDriven.NET runner against a target namespace, test classes including nested test classes in the namespace are executed.  This pull request implements similar behavior when running the TestDriven.NET runner against a target class.
@TheCloudlessSky identified the bug using the following sample class:
```cs
class CalculatorTests
{
class Adding
{
public void computes_the_sum()
{
var sut = new Calculator();
var result = sut.Add(1, 2);
result.ShouldEqual(3);
}
}
class Subtracting
{
public void computes_the_difference()
{
var sut = new Calculator();
var result = sut.Subtract(3, 2);
result.ShouldEqual(1);
}
}
}
```
This pull request ensures that when invoking TestDriven.NET on CalculatorTests, the inner types Adding and Subtracting are also considered by the applicable …
=> TestDriven.NET runner includes tests from nested classes when the user targets a type.

src/Fixie.Console/ConsoleListener.cs, src/Fixie.Console/Program.cs, src/Fixie.Console/TeamCityListener.cs, src/Fixie.Tests/AssertionLibraryFilteringTests.cs, src/Fixie.Tests/ConsoleRunner/ConsoleListenerTests.cs, src/Fixie.Tests/ConsoleRunner/TeamCityListenerTests.cs, src/Fixie.VisualStudio.TestAdapter/VisualStudioListener.cs, src/Fixie.VisualStudio.TestAdapter/VsTestExecutor.cs, src/Fixie/Execution/ExecutionEnvironment.cs, src/Fixie/Execution/LongLivedMarshalByRefObject.cs, src/Fixie/Fixie.csproj, src/Fixie/Internal/ExecutionProxy.cs
Release 1.0.0.3 (https://github.com/fixie/fixie/releases/tag/1.0.0.3) fixed a bug in which long-running tests could cause runners to fail, due to the atypical default lifetimes of MarshalByRefObjects.  The fix worked by giving such objects unlimited lifetimes (as does the NUnit Visual Studio runner, for the same reason).
However, the fix required every subclass of MarshalByRefObject to override InitializeLifetimeService() in the same way, and third-party runner authors would be left to reintroduce/diagnose/fix the same basic bug in their own code.
This pull request solves both of those problems.  Runner authors who provide their own Listener are reminded at runtime to inherit LongLivedMarshalByRefObject instead of simply inheriting MarshalByRefObject.  All built-in Listeners also inherit …
=> Simplify the pattern to properly manage MarshalByRefObjectLifetimes (primarily for implementations of Listener).

src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/VisualStudio/TestAdapter/SourceLocationProviderTests.cs, src/Fixie.Tests/VisualStudio/TestAdapter/SourceLocationSamples.cs, src/Fixie.VisualStudio.TestAdapter/Fixie.VisualStudio.TestAdapter.csproj, src/Fixie.VisualStudio.TestAdapter/SourceLocation.cs, src/Fixie.VisualStudio.TestAdapter/SourceLocationProvider.cs, src/Fixie.VisualStudio.TestAdapter/VsTestDiscoverer.cs, src/Fixie.VisualStudio.TestAdapter/packages.config, src/Fixie/Fixie.nuspec
Before this pull request, Fixie's Visual Studio test adapter did not make any attempt to report test method line numbers to Visual Studio. Without that data, the Visual Studio Test Explorer cannot navigate from a test name to the corresponding declaration, and context menus within the code editor could not determine what "Run Tests" meant.
This pull request provides line number information to Visual Studio *whenever doing so is unambiguous*.  It does so by leveraging the Mono.Cecil library for its ability to inspect assemblies without loading them into the calling AppDomain.  The NUnit and xUnit test adapters instead rely on DiaSession, defined within Microsoft.VisualStudio.TestPlatform.ObjectModel.dll, but those frameworks have had to jump through additional hoops due to DiaSession not …
=> Report Test Method Line Numbers to Visual Studio Test Adapter

src/Fixie.Samples/Explicit/CalculatorTests.cs, src/Fixie.Samples/Explicit/CustomConvention.cs, src/Fixie.VisualStudio.TestAdapter/VisualStudioListener.cs, src/Fixie.VisualStudio.TestAdapter/VsTestExecutor.cs
Due to a copy/paste error, tests skipped by Fixie would be reported as Passing in Visual Studio's Test Explorer window.  This PR fixes the issue by simply mapping the true status of the test case to Visual Studio.
Note, though, that we deliberately map Fixie's Skipped status to Visual Studio's NotRun status, instead of using Visual Studio's Skipped status.  Fixie uses "skipped" to mean "the test case itself was skipped, so it never ran", while Test Explorer treats "skipped" to mean "the test case may have run but its *result* is to be skipped from failing the build".  If we reported them as Visual Studio's Skipped status, then the UI would present them with a warning icon and would call the whole build Yellow instead of Green.  Visual Studio's NotRun status corresponds with Fixie's …
=> Report skipped tests in Test Explorer

src/Fixie.Tests/CaseTests.cs, src/Fixie/Internal/ObjectExtensions.cs
* Fixes display of string literals by properly including the "..." *inside* the quotation marks of truncated string literals.
* Fixes display of string literals to properly escape unicode line ending characters  U+0085 (Next Line), U+2028 (Line Separator), and U+2029 (Paragraph Separator) as `\u####` sequences.
* Fixes display of char literals in test case names by displaying special characters with escape sequences, including the unicode fix above.
* Phases out needlessly-complex Regex solution for a simpler loop-and-switch replacement.
=> Fix character escaping within test case names

src/Fixie.Tests/Execution/AppDomainCommunicationAssertions.cs, src/Fixie.Tests/Execution/CaseResultTests.cs, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie/Execution/CaseResult.cs, src/Fixie/Execution/FailResult.cs, src/Fixie/Execution/PassResult.cs, src/Fixie/Execution/SkipResult.cs, src/Fixie/Internal/ClassRunner.cs
To enable upcoming changes to the runner API and its use of AppDomains, this separates CaseResult from the more specific types PassResult, FailResult, and SkipResult.  The 3 specific result types allow for the Listener interface to be easy to work with, but need not inherit from CaseResult, which complicated their implementation.
=> Simplify case result type hierarchy.

src/Fixie.Console/ListenerFactory.cs, src/Fixie.Console/Program.cs, src/Fixie.Tests/Execution/AppDomainCommunicationAssertions.cs, src/Fixie.VisualStudio.TestAdapter/ListenerFactory.cs, src/Fixie.VisualStudio.TestAdapter/VsTestExecutor.cs, src/Fixie/Execution/ExecutionEnvironment.cs, src/Fixie/Execution/IListenerFactory.cs, src/Fixie/Execution/LongLivedMarshalByRefObject.cs, src/Fixie/Fixie.csproj, src/Fixie/Internal/ExecutionProxy.cs, src/Fixie/Internal/RemoteAssemblyResolver.cs
In #120, the Listener interface was separated from `AppDomain` communication so that they would stop having to be limited in the types they accept/return, and to limit the amount of code that cares about the deprecated concept of `AppDomains`.  This introduced `IExecutionSink` as a low-level interface that *did* continue to work with `AppDomains` so that Listener itself wouldn't have to.  Unfortunately, `IExecutionSink` became a declared argument on the `IListenerFactory`'s `Create` method, although *most* runners had no need for providing a concrete implemetation of `IExecutionSink`.
This pull request allows `IListenerFactory` implementations to have arbitrary constructor arguments, passed from the Fixie runner's `AppDomain` to the child `AppDomain` dedicated to each test assembly, …
=> Listener factory constructor arguments

src/Fixie.Samples/Fixie.Samples.csproj, src/Fixie.Samples/Nested/CalculatorTests.cs, src/Fixie.Samples/Nested/CustomConvention.cs, src/Fixie.Samples/SamplesAssembly.cs, src/Fixie.Samples/Skipped/CustomConvention.cs, src/Fixie.Samples/Skipped/ExplicitAttribute.cs, src/Fixie.Samples/Skipped/ExplicitClassTests.cs, src/Fixie.Samples/Skipped/SkipClassTests.cs, src/Fixie.TestDriven/TdNetRunner.cs, src/Fixie/Internal/Runner.cs
While implementing #87 to run nested test classes when TD.NET is used to invoke a single surrounding test class, I introduced a bug in which Convention.TargetMember would no longer be initialized at the class level.  If you used TD.NET to invoke a specific class, the convention wouldn't know that the class had been specifically selected for execution.  This lack of initialization would prevent a convention author from mimicking NUnit's class-level [Explicit] attributes, for instance.
This pull request fixes the initialization of TargetMember, preserves the behavior of running nested classes under TD.NET, and includes new Fixie.Samples conventions to demonstrate those scenarios.
=> Restore support for initializing TargetMember when a class is the target of a TD.NET invocation

src/Fixie.Samples/Fixie.Samples.csproj, src/Fixie.Samples/Parameterized/CustomConvention.cs, src/Fixie.Samples/Parameterized/TestCaseSourceAttribute.cs, src/Fixie.Samples/Parameterized/TestCaseSourceAttributeCalculatorTests.cs
Adding to Fixie samples - this sample adds a Fixie convention to recognize user-defined data sources for parameterized tests. *A simple implementation of [NUnit's TestCaseSource attribute][1] in Fixie.*
In this sample, I added a custom convention that recognizes my "TestCaseSource" attribute, allowing you to name the public static method, field or property that will supply the input parameters. Allows you to specify an additional parameter if the method/field/property is in another class.
*Use cases:*
* When the same test needs to be run for every value of an Enumeration
* When the same test needs to be run for all values in a set, but some inputs should result in a true condition and others in a false condition
* When the same test needs to be run for all possible combination of 2 or …
=> Test case source

src/Fixie.Console/CommandLineParser.cs, src/Fixie.Tests/ConsoleRunner/CommandLineParserTests.cs
When the console runner is invoked for an assembly whose directory does not also contain Fixie.dll, test execution halts with a message explaining that Fixie.dll must be referenced in order for the assembly to be considered a test assembly. Otherwise, the user would be presented with an unhelpful stack trace the first time Fixie.dll was expected to be found there by the child AppDomain.
=> Provide guidance to the user when the console runner is invoked for a test assembly that does not appear to reference Fixie.dll.

src/Fixie.Tests/CaseTests.cs, src/Fixie.Tests/Cases/ParameterizedCaseTests.cs, src/Fixie/Case.cs, src/Fixie/Internal/Behaviors/InvokeMethod.cs
This pull request fixes exception handling and user-facing messaging in scenarios in which parameterized generic test methods fail to execute.
Previously, when Fixie attempted to resolve the declared generic type parameters against the incoming actual test case parameter values, the attempt could fail due to violation of generic type constraints (`where T: struct`, `where T: new()`, etc). The failure produced an uncaught exception which would kill the process, and had a confusing exception message provided by Method.Invoke(...). With this PR, the exception is handled and the test case simply fails with a clear explanation.
=> Fix generic case failure scenarios

src/Fixie.Samples/MbUnitStyle/CalculatorTests.cs, src/Fixie.Samples/MbUnitStyle/CustomConvention.cs
add parameter data type converter as original MbUnit behave. one of most useful example is to change string value ie "11/22/2016" to DataTime value. so developers are able to define parameters in different/easy ways.
=> Samples.MbUnitStyle added parameter data type converter

src/Fixie/Fixie.csproj, src/Fixie/Internal/Behaviors/TimeClassExecution.cs, src/Fixie/Internal/ExecutionPlan.cs
When capturing the duration of a test case execution, we now take in
consideration the duration to create the instance of the Test Fixture.
That way, if there is expensive work being done in the test class
constructor it is captured in the CaseResult duration.
The impact of the fixture setup duration in the case duration is dependent
on the number of cases that are executed by that Test Fixture instance,
as:
````
TotalCaseDuration = CaseDuration + (FixtureSetupDuration / NumberOfCases)
````
=> Take Fixture Setup timing in consideration when calculating CaseResult duration

src/Fixie.Assertions/ReflectionShim.cs, src/Fixie.Assertions/project.json, src/Fixie.Execution/Behaviors/InvokeMethod.cs, src/Fixie.Execution/ClassDiscoverer.cs, src/Fixie.Execution/ConventionDiscoverer.cs, src/Fixie.Execution/Env.cs, src/Fixie.Execution/Listeners/AppVeyorListener.cs, src/Fixie.Execution/Listeners/NUnitXml.cs, src/Fixie.Execution/Listeners/ReportListener.cs, src/Fixie.Execution/Listeners/XUnitXml.cs, src/Fixie.Execution/ReflectionShim.cs, src/Fixie.Execution/project.json, src/Fixie.Samples/Skipped/CustomConvention.cs, src/Fixie.Tests/Execution/Listeners/AppVeyorListenerTests.cs, src/Fixie/Convention.cs, src/Fixie/Internal/RunContext.cs
This PR makes the Fixie.Execution project target both the regular .NET Framework and netstandard1.5. Because this assembly is only used internally by Fixie at runtime, and does not need to be directly referenced by end users, we're able to target a higher netstandard than Fixie.dll itself does. Doing so saves us from having to reinvent Assembly.Location.
=> Cross Platform Fixie.Execution Assembly

src/Fixie.Runner/ExecutionEnvironment.cs, src/Fixie.Runner/ExecutionProxy.cs, src/Fixie.Runner/LongLivedMarshalByRefObject.cs, src/Fixie.Runner/RemoteAssemblyResolver.cs, src/Fixie.Runner/RunnerBase.cs, src/Fixie.Runner/SourceLocationProvider.cs, src/Fixie.Runner/project.json, src/Fixie.Tests/Execution/CompoundExceptionTests.cs, src/Fixie.Tests/Execution/ExecutionEnvironmentTests.cs, src/Fixie.Tests/Execution/Listeners/NUnitXmlTests.cs, src/Fixie.Tests/Execution/Listeners/XUnitXmlTests.cs, src/Fixie.Tests/ReflectionShim.cs, src/Fixie.Tests/TestExtensions.cs
This PR does not enable cross-platform support for .NET Core testing.
The Fixie.Samples and Fixie.Tests projects still target only the full .NET Framework. Attempts to target netcoreapp1.0 in those projects *does* compile with this PR, though. At runtime, `dotnet test` fails to actually locate `dotnet-test-fixie`, though, so targeting netcoreapp1.0 in those projects is temporarily omitted. Other runtime gaps exist after that problem gets resolved as well, such as ExecutionProxy's need to load assemblies reliably without an AppDomain. Still, this PR represents the *ability* to compile all of the projects against both net45 and netcoreapp/netstandard.
=> Cross-compilable sln

build-helpers.ps1, build.ps1, nuget.config, src/Fixie.Execution/project.json, src/Fixie.Runner/project.json, src/Fixie.Samples/project.json, src/Fixie.Tests/project.json, src/Fixie/project.json
Because NuGet package references and runtime assembly loading strategies behave very differently when targeting the full .NET Framework vs targeting netcoreapp/netstandard, Fixie's own self-testing test projects must reference the code under test *as NuGet packages* rather than as normal intra-solution project references.
To date, when targeting the regular framework exclusively, regular project references were enough because that would place things like `dotnet-test-fixie.exe` in the build output folder, and `dotnet test` would know to look for `dotnet-test-fixie.exe` in that same folder.
However, when a test project targets (or *also* targets) not-full-frameworks like netcoreapp/netstandard, build output folders no longer have redundant copies of NuGet package contents nor their …
=> Self-testing projects consume the solution's own NuGet packages

src/Fixie.Tests/VisualStudio/TestAdapter/SourceLocationProviderTests.cs, src/Fixie.Tests/VisualStudio/TestAdapter/TestCaseMappingAssertions.cs, src/Fixie.Tests/VisualStudio/TestAdapter/VisualStudioDiscoveryListenerTests.cs, src/Fixie.VisualStudio.TestAdapter/Fixie.VisualStudio.TestAdapter.csproj, src/Fixie.VisualStudio.TestAdapter/SourceLocationProvider.cs
I followed the instructions, updated the files, all tests are passing, running in Visual Studio 2017 (latest update - 3) and also when running `build.cmd`.
I did not have the error for use in "another process".
Fixes #166
=> Upgrade Mono.Cecil to latest beta

build/Fixie.build.net452.props, build/Fixie.build.netcoreapp1.0.props, src/Fixie/Fixie.nuspec
The Fixie.nuspec is consistent in its naming of target frameworks for consumers targeting .NET Core.
The Fixie.nuspec avoids excessive file copies into the consumer's build output folder for consumers targeting the full .NET Framework. For the full .NET Framework, it is sufficient to place the *TestAdapter.dll and its dependencies within the lib/net452 package folder, as these will be picked up and used by Test Explorer successfully.
It appears that for .NET Core test assemblies, the *TestAdapter.dll still has to be located in the consumer's build output folder, so we continue to accomplish that via a *.props file located in the package.
=> Simplify nuget package

src/Fixie.Tests/MessagingTests.cs, src/Fixie.Tests/Utility.cs
This will help to assert that there is no additional output generated to the listeners when running empty classes that are included by a test convention.
=> Add EmptyTestClass to MessagingTests

src/Fixie.Tests/Internal/LifecycleMessageTests.cs, src/Fixie.Tests/Internal/Listeners/AppVeyorListenerTests.cs, src/Fixie.Tests/Internal/Listeners/ConsoleListenerTests.cs, src/Fixie.Tests/Internal/Listeners/TeamCityListenerTests.cs, src/Fixie.Tests/Internal/Listeners/XUnitXmlReport.xml, src/Fixie.Tests/MessagingTests.cs, src/Fixie.Tests/TestDriven/TestDrivenListenerTests.cs, src/Fixie/Internal/Listeners/TeamCityListener.cs
Because console encoding can affect the output of TeamCityListener, it has been possible for non-ASCII characters to be misinterpreted by TeamCity. The ’ character (RIGHT SINGLE QUOTATION MARK), for example, can be read by TeamCity as a an ASCII single quote ', which is meaningful in the TeamCity service message format. It and all non-ASCII characters should instead be escaped using TeamCity's own escape sequence formatting.
See https://confluence.jetbrains.com/display/TCD18/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-Escapedvalues for documentation on producing valid escape sequences.
Note: We remove 3 old unicode-related cases here because they merely produce shorthand that TeamCity happens to support. The new hex escape sequences cover those characters, so …
=> Escape non-ASCII characters in TeamCity output

src/Fixie.Tests/Cases/AsyncCaseTests.cs, src/Fixie/MethodInfoExtensions.cs, src/Fixie/ReflectionExtensions.cs
With these changes, the following types of F# test functions seem to work as expected:
1. Returning native F# async (the signature here would be `unit -> Async<unit>`):
```
let ``it should async return the expected results``() =
async {
let! result = someAsyncMethod "test"
result.ShouldBe("testtest")
}
```
2. Or the version that returns a `Task<T>`, but doesn't have the attribute that's added for `async` C# methods (the signature here would be `unit -> Task<unit>`):
```
let ``it should async return the expected results``() =
async {
let! result = someAsyncMethod "test"
result.ShouldBe("testtest")
} |> Async.StartAsTask
```
I'm not honestly sure how to easily test this without dragging F# into the tests, or writing a second test assembly in F#.
Thoughts?
=> Add support for F# methods that return Async<T> or Task/Task<T>.

src/Fixie.Tests/Assertions/AssertionExtensions.cs, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/Internal/Listeners/AppVeyorListenerTests.cs, src/Fixie.Tests/Internal/Listeners/AzureListenerTests.cs, src/Fixie/Internal/AssemblyRunner.cs, src/Fixie/Internal/AzureListener.cs, src/Fixie/Internal/Listeners/AppVeyorListener.cs, src/Fixie/Internal/Listeners/AzureListener.cs, src/Fixie/Internal/Serialization.cs
When running under Azure DevOps, test results are reported to the Azure DevOps REST API. This requires the end user set up one environment variable in order to grant access to that API. When the environment variable is not set up, the console output includes an explanation with guidance from Azure DevOps' own documentation.
Overall, the implementation mimics that of the existing AppVeyor support.
=> Azure DevOps Integration

src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/Internal/Listeners/AzureListenerTests.cs, src/Fixie/Internal/Listeners/ExceptionExtensions.cs
Fixie already attempted to remove internal implementation details from test failure stack traces. For instance, when a test fails due to an assertion, users would prefer to see the stack trace reporting the line of the assertion as the point of failure, rather than *first* seeing stack frames about Fixie's internal experience with the exception when we call `MethodInfo.Invoke()` and `ExceptionDispatchInfo.Throw()`. The attempt was written such that it fails safe: when we're uncertain about how to safely remove the implementation details, we report the full exception.
As of .NET Core 2.1, the original stack trace string was altered so that it already omitted the still-truly-present stack frame for `ExceptionDispatchInfo.Throw()`. Although that's a convenient improvement to stack traces in …
=> Clean stack traces for .NET Core 2.1+

build.ps1, src/Directory.build.props, src/Fixie.Console/Fixie.Console.csproj, src/Fixie/Fixie.nuspec
Per Nuget command line warnings and MS documentation (https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file), the Nuget package *icon url* elements are to be replaced with *icon* elements which refer to a local file copied into the package.
=> Update deprecated nuget elements

src/Fixie.Tests/Internal/BusTests.cs, src/Fixie.Tests/Internal/Listeners/AzureListenerTests.cs, src/Fixie/Internal/AssemblyRunner.cs, src/Fixie/Internal/Bus.cs, src/Fixie/Internal/Listeners/AzureListener.cs
We have had reports of sporadic failures when communicating with the Azure DevOps API. These exceptions were poorly handled, causing the entire test run to crash.
This first improves system stability for _all_ test result event listeners including the `AzureListener` so that any exception thrown reporting an event to a sink will log to the console and proceed with the remainder of the test run. In other words, plain console reporting continues and is complete, while a buggy or otherwise problematic reporting sink no longer causes the run to crash.
Specifically for Azure DevOps, we are now also mitigating the risks of these API calls failing in the first place:
1. As the API intends, we now submit test results in batches rather than one whole round trip per test case, in the hopes that the …
=> Azure DevOps API error handling

src/Fixie/Internal/AssemblyRunner.cs, src/Fixie/Internal/Listeners/AppVeyorListener.cs, src/Fixie/Internal/Listeners/AzureListener.cs, src/Fixie/Internal/Listeners/ConsoleListener.cs, src/Fixie/Internal/Listeners/PipeListener.cs, src/Fixie/Internal/Listeners/ReportListener.cs, src/Fixie/Internal/Listeners/TeamCityListener.cs
While applying the "Nullable Reference Types" feature to the Solution, some of the warnings suggested a design improvement at the point where we conditionally construct and enlist our many `Listener` types.
Here, we focus on refactoring to a Factory Method pattern to consolidate the knowledge of each third-party reporting sink, and address only those Nullable Reference Type warnings introduced by the refactoring.
=> Listener Factory Methods

src/Fixie.Tests/MessagingTests.cs, src/Fixie.Tests/ReflectionExtensionsTests.cs, src/Fixie/ReflectionExtensions.cs
1. Consolidate redundant `Has<TAttribute>()` extension methods, by recognizing their reliance on a common base type: `Type` and `MethodInfo` are both `MemberInfo`, and `MemberInfo` is the relevant `this` type in play here.
2. Add the `MemberInfo.Has<TAttribute>(out)` extension method, which provides efficient, null-safe shorthand for the common pattern of checking for the presence of a singly-applied `Attribute` and getting a reference to that `Attribute` when present. Custom conventions are likely to benefit from this shorthand. For instance, a convention that allows for a test to be skipped by applying `[Skip("Skipping until issue 234 closes.")]` can be simply expressed: "if this test case has a `SkipAttribute` then skip it for this reason".
=> Shorthand for common attribute lookup patterns in custom conventions.

.github/workflows/main.yml, appveyor.yml, azure-pipelines.yml, build-helpers.ps1, build.cmd, build.ps1
Before this PR, the build script assumed it would only be executed on Windows, and used a *.cmd shim to invoke that script via Powershell 5, invoked with the `powershell` command.
Now, we have a script that is intended to be executed with the cross-platform Powershell 7, invoked with the `pwsh` command. The script changes favor unix-style/path/separators, and make no assumptions about the current working directory, based on experimentation running the script under various CI systems and operating systems.
The build script *runs* on Windows, Ubuntu, and macOS systems, but currently only *passes* on Windows:
1. There are two normal test failures on macOS, to be addressed in a separate PR.
2. Ubuntu VM runs on GitHub Actions seem to lack prerequisites for using C# 8 features, so that is …
=> Cross-Platform Build Script

.github/workflows/main.yml, src/Fixie.Tests/Internal/Listeners/TeamCityListenerTests.cs, src/Fixie.Tests/Internal/OptionsTests.cs
Getting the build script to succeed on macOS came down to improving the expectations within two tests:
1. When command line argument parsing validates the `--report` command line argument, it correctly relies on the OS-aware `Path.GetInvalidPathChars()` method. However, the *test* of that validation used the tab character `\t` as an example of an invalid character. It turns out that tab is invalid only on Windows. After inspecting the implementation of `Path.GetInvalidPathChars()` for each OS, the null character `\0` is a better choice for the assertion as it is considered invalid everywhere.
2. The support for reporting to TeamCity correctly encodes special characters according to TeamCity's "Service Message" documentation. Although that reporting already *works* on macOS, the *test* of …
=> Enable successful builds on macOS

src/Fixie.Tests/Assertions/AssertionExtensions.cs, src/Fixie.Tests/CaseTests.cs, src/Fixie.Tests/Cases/ParameterizedCaseTests.cs, src/Fixie.Tests/Internal/GenericArgumentResolverTests.cs, src/Fixie/Internal/GenericArgumentResolver.cs
Fixie has always supported parameterized test methods, including generic test methods. To make sense of such a generic method invocation, Fixie has to figure out what concrete types replace the generic type argumets in each invocation, comparable to the type checking that would normally happen by the compiler at runtime.
For instance, given a generic test method and some presumed attribute-based `ParameterSource`:
```cs
[Input(1, "A")]
[Input("B", 'C')]
public void GenericTest<T1, T2>(T1 x, T2 y) { ... }
```
Fixie has to nail down the meaning of `T1` and `T2` once for each of the two sets of inputs. In the first invocation of the test, `T1` is `int` and `T2` is `string`. In the second `T1` is `string` and `T2` is `char`.
In Fixie v1 and v2, though, the attempts to nail down each type …
=> Improve Generic Type Argument Resolution

src/Fixie.Tests/Cases/NonVoidCaseTests.cs, src/Fixie.Tests/LifecycleTests.cs, src/Fixie.Tests/PrimaryConvention.cs, src/Fixie/Internal/ExecutionRecorder.cs, src/Fixie/TestClass.cs, src/Fixie/TestMethod.cs
Before this PR, those who customize at the deepest "test case" level had to remember to call @case.Execute() to meaningfully begin execution of the test case. Then they could proceed with evaluating the result state of the test case (to decide that it be treated as skipped, to enrich a failure message with more information, etc).
This had some flaws. It was easy to forget, needlessly verbose, and encouraged "bad behavior" such as calling @case.Execute() multiple times when the appropriate thing would be to call TestMethod.Run(...) multiple times instead. Calling @case.Execute() multiple times would pollute the meaning of tracked console output and duration measurement for the case.
This PR eliminates the need to call @case.Execute() yourself, turning the deepest customization hook from a …
=> Test Result Post-Processing

src/Fixie.Tests/Cases/BasicCaseTests.cs, src/Fixie.Tests/Cases/ParameterizedCaseTests.cs, src/Fixie.Tests/Internal/LifecycleMessageTests.cs, src/Fixie.Tests/LifecycleTests.cs, src/Fixie.Tests/TestAdapter/ExecutionListenerTests.cs, src/Fixie/Internal/TestAssembly.cs, src/Fixie/TestClass.cs, src/Fixie/TestMethod.cs
This PR satisfies the goal of providing a "full accounting" of test results even in abnormal situations.
Under normal circumstances, all tests run and all tests have a single unambiguous Pass or Fail result based on whether or not the test method throws. The story is more interesting when a convention chooses to recharacterize such a result as a Skip (a "Programmatic Skip Result"), when a convention chooses never to run a test in the first place (an "Automatic Skip Result"), or when any level of a customization throws unexpectedly (a "Lifecycle Fail Result").
In prior versions, Fixie would attempt to deliberately simplify results. A Pass or a Programmatic Skip would be suppressed if the custom lifecycle eventually threw an exception, for instance, allowing the failure to supercede the …
=> Full Accounting of Abnormal Results

src/Fixie.Tests/Cases/NonVoidCaseTests.cs, src/Fixie.Tests/Cases/ParameterizedCaseTests.cs, src/Fixie.Tests/Internal/ExecutionSummaryTests.cs, src/Fixie.Tests/Internal/TestAssemblyTests.cs, src/Fixie.Tests/LifecycleTests.cs, src/Fixie.Tests/MessagingTests.cs, src/Fixie.Tests/PrimaryConvention.cs, src/Fixie.Tests/TestClassConstructionTests.cs, src/Fixie/Internal/DefaultExecution.cs, src/Fixie/TestClass.cs, src/Fixie/TestMethod.cs
Before this PR, convention authors had to deal with an awkward method, `TestClass.RunTests(Action<TestMethod> testLifecycle)`, in order to run any tests:
```cs
public class TestingConvention : Execution
{
public void Execute(TestClass testClass)
{
testClass.RunTests(test =>
{
if (test.Method.Has<SkipAttribute>(out var skip))
{
test.Skip(skip.Reason);
return;
}
test.Run();
}); 
}
}
```
Recent improvements to the underlying model have allowed us to phase this out in favor of plain old fashioned idiomatic C#. This makes it much easier to write, reason about, and step through a convention under the debugger:
```cs
public class TestingConvention : Execution
{
public void Execute(TestClass testClass)
{
foreach (var test in testClass.Tests)
{
if (test.Method.Has<SkipAttribute>(out var skip)) …
```
=> Idiomatic Test Class Lifecycles

src/Fixie.Tests/Cases/BasicCaseTests.cs, src/Fixie.Tests/Cases/NonVoidCaseTests.cs, src/Fixie.Tests/Cases/ParameterizedCaseTests.cs, src/Fixie.Tests/Internal/MethodDiscovererTests.cs, src/Fixie.Tests/Internal/TestAssemblyTests.cs, src/Fixie.Tests/LifecycleTests.cs, src/Fixie.Tests/MessagingTests.cs, src/Fixie.Tests/SelfTestDiscovery.cs, src/Fixie.Tests/ShuffleExtensionsTests.cs, src/Fixie.Tests/TestAdapter/DiscoveryListenerTests.cs, src/Fixie.Tests/TestClassConstructionTests.cs, src/Fixie.Tests/TestExtensions.cs, src/Fixie/Internal/Configuration.cs, src/Fixie/Internal/Expressions/MethodExpression.cs, src/Fixie/Internal/MethodDiscoverer.cs, src/Fixie/ShuffleExtensions.cs
Because #235 enables flexible and idiomatic test ordering as an Execution phase concern rather than a Discovery concern, declarative ordering rules on Discovery are deprecated and removed.
Before:
```cs
public class CustomDiscovery : Discovery
{
public CustomDiscovery()
{
Methods
.OrderBy(x => x.Name);
}
}
public class CustomExecution : Execution
{
public void Execute(TestClass testClass)
{
foreach (var test in testClass.Tests)
test.Run();
}
}
```
After:
```cs
public class CustomExecution : Execution
{
public void Execute(TestClass testClass)
{
foreach (var test in testClass.Tests.OrderBy(x => x.Name))
test.Run();
}
}
```
The "Shuffle" test order randomizer is still available, now as an extension method on `IEnumerable<TestMethod>`:
```cs
public class CustomExecution : Execution
{
public …
```
=> Remove Ordering from Discovery Phase

src/Fixie.TestAdapter/VsTestExecutor.cs, src/Fixie.Tests/Internal/RunnerTests.cs, src/Fixie.Tests/PrimaryConvention.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Internal/Runner.cs, src/Fixie/TestAssembly.cs, src/Fixie/TestClass.cs
Replaces the deprecated `TargetMethod` concept with a more general purpose `SelectedTests` concept.
Historically, when a single test method was selected by a test runner like Test Explorer, the often-null `TargetMethod` property would be set to the MethodInfo of that selected test method. This originated with Fixie v1 TestDriven.NET support as a direct influence from TestDriven.NET's integration API.
This PR replaces the concept with a generalized `SelectedTests` property, an ummutable set of selected test names. Tests can be selected in various runners such as Test Explorer and at the command line with the `--tests` pattern matching filter.
=> Replace TargetMethod with SelectedTests

src/Fixie.Tests/Internal/MethodDiscovererTests.cs, src/Fixie.Tests/ReflectionExtensionsTests.cs, src/Fixie.Tests/TestClassConstructionTests.cs, src/Fixie/Internal/MethodDiscoverer.cs, src/Fixie/Internal/Runner.cs, src/Fixie/MethodInfoExtensions.cs, src/Fixie/ReflectionExtensions.cs, src/Fixie/TestMethod.cs
Previous versions include special treatment of `IDisposable` on `Discovery`, `Execution`, and test classes. When these classes implement `IDisposable`, the `Dispose()` method is naturally *not* mistaken for a test method, and it is called appropriately. If Fixie constructs such a type, Fixie is responsible for calling `Dispose()` when it is done with it. If you construct such a type yourself (a custom convention which explicitly constructs a test class), it's your job to `Dispose()`.
This PR adds the same support for the recently-added `IAsyncDisposable` interface. `IAsyncDisposable.DisposeAsync()` is not mistaken for a test method, and Fixie invokes it and awaits it appropriately for any such object that Fixie constructed on your behalf. In the bizarre case that both interfaces are …
=> Support IAsyncDisposable on conventions and test classes.

.github/workflows/ci.yml, .github/workflows/release.yml, src/Fixie.Console/Fixie.Console.csproj, src/Fixie.Tests/Fixie.Tests.csproj
Enable `RollForward=Major` for Fixie.Console, so that it can run on .NET Core 3.1 *and later versions*.
Hopefully illustrates the benefits of the change suggested in https://github.com/fixie/fixie/issues/246 
Sending a PR to verify this builds and runs as expected (GitHub actions did not run in my fork).
=> Build and run with .NET SDK 5.0

src/Fixie.Console/Fixie.Console.csproj
As suggested in https://github.com/fixie/fixie/issues/246#issuecomment-727609379, enabling `RollForward=Major` on the `master` branch, i.e. for Fixie CLI tool 2.2.1. Fixes #246 
This should unblock running Fixie 2.x tools when only later .NET Core versions (e.g. 3.x and 5) are available.
Hopefully PRs against `master` branch still work with CI.
=> Enable `RollForward=Major` for 2.2.1 (master)

src/Fixie.Tests/AssemblyLifecycleTests.cs, src/Fixie.Tests/Assertions/AssertionExtensions.cs, src/Fixie.Tests/InstrumentedExecutionTests.cs, src/Fixie.Tests/TestClassLifecycleTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Execution.cs, src/Fixie/Internal/Runner.cs
This is experimental, and may be adjusted if we address custom reports prior to 3.x leaving beta.
When customizing the test class lifecycle, you can optionally provide StartAsync() and CompleteAsync() methods, each awaited once at the start and end of the test assembly run, respectively:
```cs
public class CustomExecution : Execution
{
public Task StartAsync()
{
// One-time set up for the entire test run.
}
public async Task ExecuteAsync(TestClass testClass)
{
foreach (var test in testClass.Tests)
await test.RunAsync();
}
public Task CompleteAsync()
{
// One-time tear down for the entire test run.
}
}
```
=> Assembly start/complete customization hooks

src/Fixie.Tests/Internal/CaseTests.cs, src/Fixie.Tests/Internal/GenericArgumentResolverTests.cs, src/Fixie.Tests/PrimaryConvention.cs, src/Fixie.Tests/TestClassConstructionTests.cs, src/Fixie.Tests/TestClassLifecycleTests.cs, src/Fixie/Case.cs, src/Fixie/Internal/Case.cs, src/Fixie/Internal/CaseCompleted.cs, src/Fixie/Internal/CaseFailed.cs, src/Fixie/Internal/CasePassed.cs, src/Fixie/Internal/CaseSkipped.cs, src/Fixie/Internal/CaseStarted.cs, src/Fixie/Internal/Listeners/ExceptionExtensions.cs, src/Fixie/TestMethod.cs
This phases out the test case-level failure inspection hook as irrelevant. There were two reasons this existed:
1. So that conventions could detect and inspect exceptions for failed tests, such as to count failures as they happen.
2. To recharacterize a failure as a skip.
We improve the situation here for point 1 by providing that exception in the return value from `TestMethod.RunAsync(...)`.
We reject point 2 as anathema to Fixie v3's design intention. This ability is a workaround rather than a feature. If a user wants to interpret some exceptions as OK, it is free to do so within the test method body. If a user wanted this in order to set up a retry concept, it is free to do so idiomatically within the test method body and is free to use a library like Polly to do so cleanly. A test …
=> Drop deprecated failure inspection hook

build/Fixie.props, build/Fixie.targets, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec
Our understanding is that the reason JetBrains hasn't detected our VSTest Test Adapter in the past is that we have until now deliberately avoided the Microsoft.NET.Test.Sdk nuget package.
That package introduces an empty `Main()` method into your test project. The Fixie.TestAdapter itself injects a *non-empty* `Main()` method to actually run the test project.
Since we are introducing a dependency on Microsoft.NET.Test.Sdk, we wind up with two Main() methods. This PR then compensates for that by attempting to disable the Microsoft.NET.Test.Sdk's own code generation step before it has a chance to happen.
Microsoft.NET.Test.Sdk also has the undesirable effect of incorrectly treating the Fixie.TestAdapter project as unpackable (a reasonable impact on test projects that are rarely packed, but …
=> JetBrains ReSharper/Rider Integration

.github/workflows/ci.yml, .github/workflows/release.yml, global.json, src/Fixie.Tests/TestProject.cs, src/Fixie/Reports/ConsoleReport.cs
In the event that no tests are found, either by failing to meet the Discovery convention in effect, or by poorly implementing a custom Discovery convention such that no tests are found, Fixie already outputs a clear explanation and returns a fatal exit code so that the build will fail. This PR improves the user's ability to scan and diagnose that problem when looking at their build output.
=> Enhance Fatal Error Communication

src/Fixie.Tests/DiffToolReport.cs, src/Fixie.Tests/Fixie.Tests.csproj
This does not affect end users, but does improve upon the recommended pattern of using diff tools for development-time test failure reporting.
Instead of relying on brittle inspection of git config in order to infer the developer's diff tool of choice, we now delegate to the superior DiffEngine library.
=> DiffEngine reporting

.github/workflows/ci.yml, .github/workflows/release.yml, build.ps1, global.json, src/Directory.Build.props, src/Fixie.Tests/Fixie.Tests.csproj
This revises the handling of SDK versions used at development time as well as the TargetFramework behavior at self-testing execution time.
This uses the latest net6.0 SDK for builds, but precisely does NOT update any TargetFramework to use net6.0 at runtime as that is a distinct concept especially for Fixie, with much larger ramifications in the implementation, nuget packaging, supported targets for consumers, and the roadmap in general.
In short, this dramatically improves the CI/CD approach so that we have fewer places to update as we adopt and drop TargetFrameworks over time.
Details:
1. Avoid specifying LangVersion explicitly, as the default behavior ensures using the latest language version compatible with each target framework indicated in csproj files, so that we no longer need to …
=> Build with dotnet SDK 6

build.ps1, src/Fixie.Console/Fixie.Console.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie/Fixie.csproj
While experimenting with mult-targeting the Fixie.TestAdapter project, a bug in our old MinVer reference appeared which prevented that package from getting an appropriate version number. Thankfully a simple upgrade of MinVer addresses the issue. Additionally, the newer version of MinVer no longer requires an additional workaround in our build script, so we can simplify all `dotnet pack` lines to be alike.
Steps Taken:
1. Reveal a bug in version numbering by pluralizing `TargetFramework` to `TargetFrameworks` within Fixie.TestAdapter:
Unlike typical projects, Fixie.TestAdapter is packaged with the combination of `dotnet pack` and a manual `*.nuspec` file. Although that is generally supported, the moment we pluralize to `TargetFrameworks` MinVer fails to pick up on the intended version and …
=> Upgrade MinVer in preparation for including target framework net6.0

.github/workflows/ci.yml, .github/workflows/release.yml, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/Reports/AppVeyorReportTests.cs, src/Fixie.Tests/Reports/AzureReportTests.cs, src/Fixie.Tests/Reports/XmlReportTests.cs, src/Fixie.Tests/StackTracePresentationTests.cs, src/Fixie.Tests/TestClassConstructionTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Fixie.csproj, src/Fixie/Internal/Serialization.cs
As follow-up to #287 (Build with dotnet SDK 6), this officially includes target framework net6.0.
Prior to this, Fixie did already *work* with net6.0 consumer solutions, but adding the target does ensure that we're fully leveraging net6.0 when possible, and ensures that our own test coverage truly reveals any behavior changes between netcoreapp3.1 and net6.0.
Note that we did miss ever explicitly targeting net5.0. That was less than ideal in hindsight, but since it has already left the Microsoft support window we're skipping it intentionally.
This PR was kept focused to the minimal and ordered steps necessary to add a target framework, so that when we soon add net7.0 we'll have a clear model to follow. The lessons learned are now also documented at [Contributing to …
=> Add target framework net6

src/Fixie.Tests/GitHubReport.cs, src/Fixie.Tests/TestProject.cs
The GitHubReport provides a short color-coded ["Job Summary"](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) so that developers can quickly inspect their completed job without having to look into the step logs.
Sample output for a solution mult-targeting different frameworks:
🔴 No tests found.
🟢 140 passed
🟡 139 passed, 1 skipped
🔴 138 passed, 1 skipped, 1 failed
=> The GitHubReport provides a short color-coded "Job Summary"

.github/workflows/ci.yml, .github/workflows/release.yml, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/StackTracePresentationTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Fixie.csproj, src/Fixie/Reports/ExceptionExtensions.cs
This adds target framework `net7.0` where appropriate:
* Ensure that the GitHub Actions build environment includes the .NET 7 SDK.
* Add target framework `net7.0` to the `Fixie`, `Fixie.TestAdapter`, and `Fixie.Tests` projects.
* Mirror `Fixie.TestAdapter` csproj changes in the corresponding nuspec.
* Deliberately leave the `Fixie.Console` project targeting our support window lower bound of `netcoreapp3.1`. As a `dotnet ...` tool definition, we target low and already compensate for that with `RollForward` behavior.
* Address all test failures that appeared while running on `net7.0`.
The primary novel change accounted for here on `net7.0` runs comes in the method that cleans up a test failure stack trace for presentation. Here, we aim to present a stack trace where execution apparently …
=> Add target framework net7.0

.github/workflows/ci.yml, .github/workflows/release.yml, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/ReflectionExtensionsTests.cs, src/Fixie.Tests/StackTracePresentationTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Fixie.csproj, src/Fixie/Reports/ExceptionExtensions.cs
This adds target framework `net8.0` where appropriate:
* Ensure that the GitHub Actions build environment includes the .NET 8 SDK.
* Add target framework `net8.0` to the `Fixie`, `Fixie.TestAdapter`, and `Fixie.Tests` projects.
* Mirror `Fixie.TestAdapter` csproj changes in the corresponding nuspec.
* Deliberately leave the `Fixie.Console` project targeting our support window lower bound of `netcoreapp3.1`. As a `dotnet ...` tool definition, we target low and already compensate for that with `RollForward` behavior.
* Address all test failures that appeared while running on `net8.0`.
The primary novel change accounted for here on `net8.0` runs comes in the method that cleans up a test failure stack trace for presentation. Here, we aim to present a stack trace where execution apparently …
=> Add target framework net8

.gitignore, .vscode/launch.json, .vscode/tasks.json, build.ps1, release.ps1, src/Directory.Build.props, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec
The .NET 8 SDK adds support for "Artifacts Output Layout", which moves the per-project support folders like `bin/` and `obj/` to a common location outside of the project folders, as well as adjusting naming conventions around Configuration (Release, Debug...) and Target Framework Monikers (net8.0, ...).
Although the feature arrives in the .NET 8 SDK, it works for projects that target older frameworks, so this is appropriate even before the upcoming phasing-out of old frameworks.
We enable the feature, simplify `.gitignore`, and visit all hardcoded paths affected by the move.
Additionally, since this creates some ambiguity of purpose between the new `src/artifacts/` folder and our root `artifacts` folder where packages are output during CI builds, we rename that root folder to the more …
=> Enable "Artifacts Output Layout".

src/Fixie.TestAdapter/ArgumentNullExceptionShim.cs, src/Fixie.TestAdapter/TestAssembly.cs, src/Fixie.TestAdapter/VsTestExecutor.cs
As a step toward ensuring absolutely-reliable assembly loading during debugger-attached test runs, *even for incomplete third-party runners*, here we simplify the Test Adapter implementation in the area where those resiliency changes are planned.
This is a refactoring in the strict sense of the words. The purpose of doing this in a dedicated Pull Request is to get the behavior-sustaining cleanup reviewed in isolation and to make that upcoming behavior-changing work easier to understand and review independent of these "superficial" changes.
=> Simplify Test Adapter Prior to Resiliency Updates

src/Fixie.TestAdapter/DebuggerAttachmentFailure.cs, src/Fixie.TestAdapter/LoggingExtensions.cs, src/Fixie.TestAdapter/TestAssembly.cs, src/Fixie.TestAdapter/VsTestDiscoverer.cs, src/Fixie.TestAdapter/VsTestExecutor.cs
This PR ensures Test Adapter resiliency in the face of faulty third party `LaunchProcessWithDebuggerAttached` implementations. It is a replacement for the earlier attempts at resiliency removed in #300 and #301.
In the past, I made the mistake of attempting to work around such debugger-attachment issues to the detriment of the project. I added workarounds intended to smooth over third party gaps, in fact dropping end users into bizarre assembly loading issues instead of driving them directly to success. I added workarounds intended to allow expected behavior for as many test runners as possible, only to find later that the Test Adapter was throwing exceptions that left their UX stuck spinning or reporting "inconclusive" results. In each case, in addition to creating false solutions, the …
=> Third Party Test Runner Resiliency

src/Fixie.Tests/Internal/TestPatternTests.cs, src/Fixie/Internal/TestPattern.cs
The `dotnet fixie` filtering argument `--tests` was introduced in https://github.com/fixie/fixie/pull/238. Although it behaved well in many cases, it had an implicit wildcard at the end of the given pattern, and *when* that didn't match the user's expectations they had no recourse. Here, we fix the semantics of this argument so that all users can achieve their desired filter:
* Users who want to precisely match a test, even if there are similar tests nearby with varying suffixes, can now do so simply by stating the name of the test they are filtering to.
* Users who instead wanted to include nearby tests with varying suffixes are free to include an explicit wildcard.
I debated whether this should be treated as a breaking change or not, which could push the fix into the future 4.x line. …
=> Fix `--tests` pattern matching semantics

.github/workflows/ci.yml, .github/workflows/release.yml, src/Directory.Build.props
This is a simple versioning bump marking the start of v4 development. We use MinVer to version assemblies and packages. To ensure that the alpha builds for upcoming commits start with major version `4.0` instead of simply adding height to the most recent `3.*` tag, we update an MSBuild property to the desired *Major.Minor* value `4.0`.
While doing this, a scan of the latest documentation from MinVer showed an opportunity to improve the performance of the clone performed in GitHub Actions. We still need the full set of commits to guarantee MinVer's calculation, but now we omit all excessive tree (folder) and blob (file) data from the historic commits.
=> Update versioning to begin v4 development

.github/workflows/ci.yml, .github/workflows/release.yml, src/Fixie.Console/Fixie.Console.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/ReflectionExtensionsTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Fixie.csproj, src/Fixie/Reports/ExceptionExtensions.cs
This phases out deprecated target framework `net6.0`, which will not pass the end of it's own support window until November 12, 2024.
The rationale is that Fixie 4.0 is intended to be released sometime during 2024 and close enough to the end of the `net6.0` lifetime to warrant dropping it in favor of modern C# and .NET features. By that point most users who tend towards upgrading things will have done so to the latest LTS framework (`net8.0`), and those who don't tend towards upgrading things will continue to be served by Fixie 3.x, which will never drop an already-supported target framework.
This raises the "floor" for the solution from `net6.0` and `C# 10` to `net7.0` and `C# 11`.
=> Remove target framework `net6.0`

.github/workflows/ci.yml, .github/workflows/release.yml, src/Fixie.Console/Fixie.Console.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/ReflectionExtensionsTests.cs, src/Fixie.Tests/StackTracePresentationTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Fixie.csproj, src/Fixie/Reports/ExceptionExtensions.cs
This phases out deprecated target framework `net7.0`, which will not pass the end of it's own support window until May 14, 2024.
The rationale is that Fixie 4.0 is intended to be released sometime during 2024 and either close to or beyond the end of the `net7.0` lifetime, warranting dropping it in favor of modern C# and .NET features.
This raises the "floor" for the solution from `net7.0` and `C# 11` to `net8.0` and `C# 12`.
=> Remove target framework `net7.0`

src/Fixie.Console/CommandLine.cs, src/Fixie.Console/NamedArgument.cs, src/Fixie.Console/Parser.cs, src/Fixie.TestAdapter/VsTestExecutor.cs, src/Fixie.Tests/Assertions/AssertionExtensions.cs, src/Fixie.Tests/Console/ParserTests.cs, src/Fixie.Tests/GitHubReport.cs, src/Fixie.Tests/Internal/ExecutionSummaryTests.cs, src/Fixie.Tests/Internal/GenericArgumentResolverTests.cs, src/Fixie.Tests/Internal/JsonSerializationTests.cs, src/Fixie.Tests/Internal/RunnerTests.cs, src/Fixie.Tests/Reports/AppVeyorReportTests.cs, src/Fixie.Tests/Reports/AzureReportTests.cs, src/Fixie.Tests/Reports/LifecycleMessageTests.cs, src/Fixie.Tests/StubReport.cs, src/Fixie.Tests/TestAdapter/VsDiscoveryRecorderTests.cs, src/Fixie.Tests/TestAdapter/VsExecutionRecorderTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/ConventionCollection.cs, src/Fixie/Internal/GenericArgumentResolver.cs, src/Fixie/Internal/Runner.cs, src/Fixie/ReportCollection.cs, src/Fixie/Reports/ConsoleReport.cs, src/Fixie/Reports/XmlReport.cs, src/Fixie/Test.cs, src/Fixie/TestEnvironment.cs
This applies collection literals across the solution, but only for cases where the empty literal `[]` applies.
Limiting the scope to only empty collections keeps the scope of the PR within reason for review. Furthermore, it is meant to be reviewed one commit at a time, as each commit is dedicated to a single syntax pattern being transformed. Each commit identifies which parts were made by automated refactorings: the only manual change being commit 1 where the following pattern *could* have had an automated refactoring available, but simply doesn't: `Array.Empty<...>()` to `[]`.
=> Apply collection literal `[]` for all empty collections.

src/Fixie.Console/Parser.cs, src/Fixie.Console/Program.cs, src/Fixie.Console/Shell.cs, src/Fixie.TestAdapter/SourceLocationProvider.cs, src/Fixie.TestAdapter/TestAssembly.cs, src/Fixie.Tests/Assertions/AssertException.cs, src/Fixie.Tests/Console/ParserTests.cs, src/Fixie.Tests/InstrumentedExecutionTests.cs, src/Fixie.Tests/Internal/BusTests.cs, src/Fixie.Tests/Internal/ClassDiscovererTests.cs, src/Fixie.Tests/Internal/JsonSerializationTests.cs, src/Fixie.Tests/Internal/RunnerTests.cs, src/Fixie.Tests/ParameterizationTests.cs, src/Fixie.Tests/ResultEmittingTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Internal/GenericArgumentResolver.cs, src/Fixie/MethodInfoExtensions.cs
This applies collection literals across the solution, but only for cases where the populated literal `[item, item, ...]` applies.
It is meant to be reviewed one commit at a time, as each commit is dedicated to a single syntax pattern being transformed. Each commit identifies that it was made entirely by automated refactorings.
=> Apply collection literal [...] for all compatible populated collection initialization.

src/Fixie.Console/Program.cs, src/Fixie.Console/Shell.cs, src/Fixie.TestAdapter/TestAssembly.cs, src/Fixie.Tests/ParameterizationTests.cs, src/Fixie/Internal/Bus.cs, src/Fixie/Internal/EntryPoint.cs
This applies collection literals in nontrivial situations, where the overall result is a simplification for readability.
It is meant to be reviewed one commit at a time, as each commit is dedicated to a single transformation/concept.
=> Apply collection literals in nontrivial situations.

src/Fixie.Tests/Internal/JsonSerializationTests.cs, src/Fixie/Internal/PipeMessage.cs, src/Fixie/Reports/TestAdapterReport.cs
When nullable reference types were first enabled, the `PipeMessage` message types presented an annoyance. Their setters were naturally public `{ get; set; }`, though we wanted to declare the property types as non-null. Careful tracing of code paths confirmed that by the time they would be inspected, they really would be non-null. Having to mark them with `?` would have needlessly spread unrealistic warnings to their usages, so instead we marked them all with the "confident assertion" `{ get; set; } = default!`.
Since then C# has added two useful keywords which better help express and enforce the intention of these "serializable property bucket" types. Here we apply both of them:
1. `init` as an alternative to `set`, communicating that they are intended to be populated during …
=> Modernize pipe message models' nullability declarations.

src/Fixie.Tests/Internal/JsonSerializationTests.cs, src/Fixie.Tests/Internal/PipeMessageSerializationTests.cs, src/Fixie.Tests/TestAdapter/VsExecutionRecorderTests.cs, src/Fixie/Internal/PipeMessage.cs, src/Fixie/Internal/TestAdapterPipe.cs
`PipeMessage` message deserialization has until now worked by calling `JsonSerializer.Deserialize<T>(string)` directly, which can return `null` in the case that the incoming string is the json literal "null". This has two unfortunate consequences:
1. Callers need to insist that the result for pipe messages in particular is not null by marking the call site with `!`, or else the nullability could spread from there.
2. In order to do so confidently, all calls to `JsonSerializer.Deserialize<T>(string)` need to be reviewed, whether relevant to these pipe messages or not, in order to instill the confidence to declare `!` accurately. In fact, all of the pipe messages deserialized come from sources that would not be null during serialization, but it's been a nontrivial analysis each time.
This …
=> Non null pipe deserialization

src/Fixie.Console/Program.cs
This trivially converts `dotnet fixie`'s `Program.cs` to Top Level Statements style. It is meant to be reviewed commit by commit. The first commit makes minimal touches to the file to technically convert to Top Level Statements, while avoiding whitespace changes that would complicate review. The second commit is a whitespace-only change where only excessive indentation is removed.
=> Convert `dotnet fixie` to Top Level Statements

src/Fixie/Internal/ExecutionRecorder.cs, src/Fixie/Internal/Runner.cs
This moves all `IReport` execution to a dedicated background thread. Partly, this is to improve test run performance even when tests are run in a single-threaded `IExecution`. Additionally, this is a step towards enabling test runner stability in the presence of a hypothetical parallel `IExecution`, though this PR does not finalize that stability. The `IReport` event processing itself becomes stable, with each message processed in safe sequence, but all mutable state in `ExecutionRecorder` (test counts and durations) would still pose issues in parallel runs.
=> Dedicated reporting thread

src/Fixie.Console/Foreground.cs, src/Fixie.Tests/InstrumentedExecutionTests.cs, src/Fixie.Tests/Internal/RunnerTests.cs, src/Fixie.Tests/MethodInfoExtensionsTests.cs, src/Fixie.Tests/Reports/AppVeyorReportTests.cs, src/Fixie.Tests/Reports/XmlReportTests.cs, src/Fixie.Tests/TestProject.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Internal/Foreground.cs, src/Fixie/Test.cs
This finalizes the ability to run Fixie's own self tests under a parallelizing custom `IExecution`.
The primary obstacle here was one test class base that relied heavily on a few static fields and temporal coupling so that hypothetical test suites could be run under instrumentation. The solution was to pivot from static fields to a containing object managed via `AsyncLocal<T>`, allowing each scenario to have an ephemeral global-feeling context of its own.
=> Parallel self testing

src/Fixie.Console/Foreground.cs, src/Fixie.Console/Program.cs, src/Fixie.Tests/Reports/AppVeyorReportTests.cs, src/Fixie.Tests/Reports/AzureReportTests.cs, src/Fixie.Tests/Reports/ConsoleReportTests.cs, src/Fixie.Tests/Reports/XmlReportTests.cs, src/Fixie.Tests/StackTracePresentationTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Internal/EntryPoint.cs, src/Fixie/Internal/Foreground.cs, src/Fixie/Reports/ConsoleReport.cs, src/Fixie/TestEnvironment.cs
Reports wanting to output the target framework of the test assembly have historically accessed `TestEnvironment.TargetFramework` which has only approximated the value by looking up the insufficient `TargetFrameworkAttribute` in the assembly's metadata. This results in strings such as ".NETCoreApp,Version=v8.0" where users would expect and prefer "net8.0" as appears literally in the csproj. This assembly metadata is also "lossy" with respect to less common target framework monikers like "net8.0-windows", where the OS suffix information would be lost.
This PR improves the values of `TestEnvironment.TargetFramework` in two ways:
1. Since `dotnet fixie` has 100% accurate access to the values in the csproj, we use this value verbatim during console runs.
2. When we are not running through …
=> Improve target framework reporting

src/Fixie.Tests/Assertions/AssertionExtensions.cs, src/Fixie.Tests/Internal/BusTests.cs, src/Fixie.Tests/Internal/ClassDiscovererTests.cs, src/Fixie.Tests/Internal/GenericArgumentResolverTests.cs, src/Fixie.Tests/Internal/MethodDiscovererTests.cs, src/Fixie.Tests/Internal/RunnerTests.cs, src/Fixie.Tests/Reports/AppVeyorReportTests.cs, src/Fixie.Tests/Reports/AzureReportTests.cs, src/Fixie.Tests/Reports/ConsoleReportTests.cs, src/Fixie.Tests/Reports/LifecycleMessageTests.cs, src/Fixie.Tests/Reports/TeamCityReportTests.cs, src/Fixie.Tests/StackTracePresentationTests.cs, src/Fixie.Tests/TestAdapter/VsDiscoveryRecorderTests.cs, src/Fixie.Tests/TestAdapter/VsExecutionRecorderTests.cs
Before we can upgrade assertions to use `[CallerArgumentExpression(...)]`, we first have to get our deprecated use of `params` arguments on those assertions out of the way. Use of `params` prevents use of subsequent default arguments like `[CallerArgumentExpression(...)]`, but thankfully the existence of collection expressions essentially invalidates `params` arguments as a concept. The tradeoff is easy, making each assertion's intention more clear while opening the door to `[CallerArgumentExpression(...)]` improvements in the next PR.
=> Phase out assertion params keyword

src/Fixie.Tests/Assertions/AssertException.cs, src/Fixie.Tests/Assertions/AssertionExtensions.cs, src/Fixie.Tests/Assertions/AssertionTests.cs, src/Fixie.Tests/Internal/RunnerTests.cs, src/Fixie.Tests/MethodInfoExtensionsTests.cs, src/Fixie.Tests/Reports/AppVeyorReportTests.cs, src/Fixie.Tests/Reports/AzureReportTests.cs, src/Fixie.Tests/Reports/ConsoleReportTests.cs, src/Fixie.Tests/Reports/LifecycleMessageTests.cs, src/Fixie.Tests/Reports/MessagingTests.cs, src/Fixie.Tests/Reports/TeamCityReportTests.cs, src/Fixie.Tests/Reports/XmlReportTests.cs, src/Fixie.Tests/ReturnTypeTests.cs, src/Fixie.Tests/TestAdapter/TestCaseMappingAssertions.cs, src/Fixie.Tests/TestAdapter/VsDiscoveryRecorderTests.cs, src/Fixie.Tests/TestAdapter/VsExecutionRecorderTests.cs
This dramatically improves the formatting of assertion messages, similar to that of Shouldly, but by letting the compiler do all of the work of obtaining a perfect "left of the dot" actual expression string via `[CallerArgumentExpression(...)]`. This is a step towards elevating these self-testing assertion helpers to a first class library of their own.
=> Descriptive assertions

src/Fixie.Tests/InstrumentedExecutionTests.cs, src/Fixie.Tests/Internal/BusTests.cs, src/Fixie.Tests/Reports/AppVeyorReportTests.cs, src/Fixie.Tests/Reports/AzureReportTests.cs, src/Fixie.Tests/Reports/ConsoleReportTests.cs, src/Fixie.Tests/Reports/LifecycleMessageTests.cs, src/Fixie.Tests/Reports/MessagingTests.cs, src/Fixie.Tests/Reports/TeamCityReportTests.cs, src/Fixie.Tests/Reports/XmlReportTests.cs, src/Fixie.Tests/StackTracePresentationTests.cs, src/Fixie.Tests/TestAdapter/VsExecutionRecorderTests.cs, src/Fixie.Tests/TestExtensions.cs
This phases out the obfuscation of what are really multiline string assertions, using the 'raw string literals' syntax.
=> Improve string assertions

src/Fixie.Tests/Assertions/AssertException.cs, src/Fixie.Tests/Assertions/AssertionExtensions.cs, src/Fixie.Tests/Assertions/AssertionTests.cs, src/Fixie.Tests/DiffToolReport.cs
When asserting on string equality, failure messaging uses reliable C# string literal formatting for the values in question. For single line strings, "normal literals" are used. For multiline strings,
"""
raw literals
"""
are used. When the string in question includes a mix of line endings, "normal literals" are used so that individual line ending characters can still be easily compared by the developer.
Examples:
```
example should be "z☺" but was "a☺"
```
```
example should be
"""
Line 1
Line 2
Line 3
Line 4
"""
but was
"""
Line 1
Line 2 OOPS
Line 3
Line 4
"""
```
```
example should be "\r \n \r\n \r \r" but was "\r \n \r\n \n \r"
```
=> String assertion messaging

.github/workflows/ci.yml, .github/workflows/release.yml
We've been getting the following warning on our use of slightly out of date github actions dependencies:
> Annotations
> 1 warning
> ci
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/setup-dotnet@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> Update actions/setup-dotnet to the latest version.

src/Fixie.Tests/Assertions/AssertException.cs, src/Fixie.Tests/Assertions/AssertionTests.cs
This fixes the rendering of raw string literals as appears in assertion exception messages.
1. Indentation uses spaces instead of tabs. Before this, it was too easy to have a failing multiline string assertion where the stated "expected... but was..." string literals appeared to be identical as they only differed in superficial whitespace. This may have only affected the self-testing of assertion methods themselves, but was annoying enough to warrant fixing.
2. Properly surrounds raw string literals in an appropriate number of `"""` double quotes, respecting the longest sequence of double quote characters in the string content.
3. Avoids incorrectly handling escape sequences in the string content. Raw strings precisely aren't about escape sequences.
=> Assertion failure readability

src/Fixie.Tests/Reports/ConsoleReportTests.cs, src/Fixie.Tests/Reports/TeamCityReportTests.cs, src/Fixie.Tests/Reports/XmlReportTests.cs, src/Fixie.Tests/StackTracePresentationTests.cs, src/Fixie.Tests/TestExtensions.cs, src/Fixie.Tests/Utility.cs
This simplifies needless complexity from tests, where absolute paths that appear in stack traces would be normalized, and then again when asserting on those values so that normalized values would be compared to normalized values. This was all originally in service of unpredictable absolute paths based on where the developer clones the repo to, as well as variations cross platform. The solution instead is to avoid interfering in the first place, and to simply calculate expectations in a platform agnostic way.
=> Simplify test comparison fakery

src/Fixie.Tests/Assertions/AssertException.cs, src/Fixie.Tests/Assertions/AssertionExtensions.cs, src/Fixie.Tests/Assertions/AssertionTests.cs, src/Fixie.Tests/Reports/AppVeyorReportTests.cs, src/Fixie.Tests/Reports/AzureReportTests.cs, src/Fixie.Tests/Reports/LifecycleMessageTests.cs, src/Fixie.Tests/TestAdapter/TestCaseMappingAssertions.cs
1. Test coverage and improved error message grammar for `ShouldNotBeNull()`.
2. Phase out the need for silly assertion explosion (`ShouldBeGreaterThan`, `ShouldBeGreaterThanOrEqualTo`, ...) in favor of a flexible lambda assertion:
An assertion like:
```cs
int.Parse(fail.DurationMilliseconds).Should(x => x >= 0);
```
Results in messages like:
```
int.Parse(fail.DurationMilliseconds) should be >= 0 but was -1000
```
=> Flexible assertions

nuget.config, src/Directory.Packages.props, src/Fixie.Console/Fixie.Console.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.sln, src/Fixie/Fixie.csproj
This establishes modern supply chain controls and uses them to simplify the solution:
* Enable Package Source Mapping
* Enable Central Package Management
* Simplify the application of MinVer to all projects using a GlobalPackageReference.
Verified version numbers still appear on assemblies and nuget packages.
=> Modern supply chain management

src/Fixie/Reports/TeamCityReport.cs
Background: During test runs under TeamCity, every testing event is written to standard out using a TeamCity specific format so that they can be picked up and extracted from the log by TeamCity for special presentation in the Tests reporting screen. The `TeamCityReport` has been largely untouched since inception, and a few language features have since become available to improve performance and readability in the implementation.
This improves performance in several ways, largely focusing on the now-available string interpolation syntax and the low level optimizations that the compiler provides for such literals. After moving to that syntax, it became clear that there were a few more opportunities for improvement, largely around avoiding redundant or irrelevant attempts to escape …
=> Modernize TeamCity Report

src/Fixie.Tests/TestEnvironmentTests.cs, src/Fixie.Tests/Utility.cs, src/Fixie/Internal/EntryPoint.cs, src/Fixie/TestEnvironment.cs
`TestEnvironment` has historically received the test assembly and a string indicating the full folder path in which the assembly lives, so that custom reports can have access to it such as for saving a report file beside the test assembly. In practice, this was the test process's current directory (at time of test assembly Main() entry). To reduce the risk of ever passing in an incorrect value, this is now calculated from the `Assembly` instance, which already knows the full path to the assembly.
=> Calculate `TestEnvironment.RootPath` instead of relying on the caller to pass it in correctly.

src/Fixie.Console/CommandLine.cs, src/Fixie.Tests/Console/CommandLineTests.cs
This modernizes `CommandLine.Partition` as it is a natural fit for `..` spread operators and collection literals. This work also reveals and then fixes an unintentional omission of any `"--"` that happen to appear within the custom arguments after the initial substantive `"--"` separator argument.
=> Modernize `CommandLine.Partition`

src/Fixie/Internal/Runner.cs
This refactors the code for taking the discovered test methods and further filtering them down by either selected tests (ie IDE tree selections) or a filter pattern (command line `--tests`. The old implementation was needlessly complex, preoccupied with reducing allocations of many short-lived lists. The simpler solution also avoids building excessive lists, but does so by simply conditionally building up a a lazy `IEnumerable<MethodInfo>` LINQ query that can be iterated once.
=> Simplify runner filtering

src/Fixie.Tests/CaseNameTests.cs, src/Fixie.Tests/MethodInfoExtensionsTests.cs, src/Fixie.Tests/ParameterizationTests.cs, src/Fixie.Tests/ReturnTypeTests.cs, src/Fixie/MethodInfoExtensions.cs
There are many reasons why an attempt to invoke an arbitrary method via reflection might fail, so for a long time now we've had a helper for ensuring that a given MethodInfo is not only invoked, but properly awaited, and properly complained about if the caller does anything atypical to thwart this effort such as using `async void` or if the method returns an unusable null or nonstarted Task. Historically, these exception messages have been clear and descriptive, but only included the method's short name when referring to the offending method. In common scenarios that was sufficient, but in the case of parameterized overloaded tests and especially in the case where one or more of those overloads is generic, the short name in the error puts more work on the developer to diagnose what test …
=> Method invocation error signatures

release.ps1
When third party forks submit pull requests, the github actions workflow builds and runs tests, and then on success attempts to publish to a developer builds package feed. Since such forks correctly cannot push to that feed, those attempts fail. This makes the PR appear at first to be in a bad state such as for a failing test, even when it's truly ready for review.
This PR alters the workflows so that we don't even bother attempting the package push when not applicable.
=> GitHub Actions workflows skip deployment attempts (which would safely fail anyway) for forks

src/Fixie.Tests/CaseNameTests.cs, src/Fixie/Internal/CaseNameBuilder.cs
This improves the handling of C# values serialized when building the name of a parameterized case, based on lessons learned during the development of rich serialization in the separate Fixie.Assertions repo.
1. Bools are serialized with the same lowercase as their keyword.
2. `\uxxxx` four-digit unicode escape sequences are used for all control characters and whitespace characters that do not already have a more terse unambiguous representation in char/string literals. Single-character escape sequences and the literal space " " take precedent, otherwise control/whitespace characters appear with `\uxxxx` format.
=> Refine case names

.github/workflows/ci.yml, .github/workflows/release.yml, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/Utility.cs, src/Fixie/Fixie.csproj
This adds target framework `net9.0` where appropriate:
- Ensure that the GitHub Actions build environment includes the .NET 9.0 SDK.
- Add target framework `net9.0` to the `Fixie`, `Fixie.TestAdapter`, and `Fixie.Tests` projects.
- Deliberately leave the `Fixie.Console` project targeting our support window's lower bound of `net8.0`. As a `dotnet ...` tool definition, we target the lower bound and already compensate for that with `RollForward` behavior.
- Mirror `Fixie.TestAdapter` csproj changes in the corresponding nuspec.
- Address all test failures that appeared while running on `net8.0`.
- This often involves changes to the careful cleanup of stack traces so that assertion failures are not complicated by `Method.Invoke` minutia, but this time it was limited to making sure that any …
=> Add target framework `net9.0`.

src/Fixie.Tests/CaseNameTests.cs, src/Fixie/Internal/CaseNameBuilder.cs
String and char serialization in parameterized case names respects the `'\e'` escape sequence introduced in C# 13. For earlier C# versions, continue to use the supported sequence `\u001B`.
=> Escape the Escape Character

src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec, src/Fixie.Tests/Internal/SourceLocationProviderTests.cs, src/Fixie.Tests/Internal/SourceLocationSamples.cs, src/Fixie.Tests/TestAdapter/SourceLocationProviderTests.cs, src/Fixie/Fixie.csproj, src/Fixie/Internal/SourceLocation.cs, src/Fixie/Internal/SourceLocationProvider.cs
The upcoming pivot from the legacy MS Test SDK to the new MS Testing Platform involves dropping the deprecated `Fixie.TestAdapter` project in favor of the modern equivalent. Prior to dropping that project, though, we want to salvage the last useful aspect of it which may come in handy during the MS Testing Platform integration: `SourceLocationProvider`'s ability to infer line numbers for test methods.
Early experimentation with MS Testing Platform suggests that in at least some circumstances, we won't need to calculate line numbers ourselves anymore. However, some of that testing revealed that allowing the test platform to do the work for us is inconsistent (as soon as we started to explicitly indicate which test method we discovered, instead of relying only on the implication of its …
=> Move SourceLocationProvider from deprecated `Fixie.TestAdapter` project to `Fixie` project.

src/Fixie.TestAdapter/VsDiscoveryRecorder.cs, src/Fixie.TestAdapter/VsTestDiscoverer.cs, src/Fixie.Tests/Internal/PipeMessageSerializationTests.cs, src/Fixie.Tests/TestAdapter/VsDiscoveryRecorderTests.cs, src/Fixie/Internal/EntryPoint.cs, src/Fixie/Internal/PipeMessage.cs, src/Fixie/Internal/SourceLocation.cs, src/Fixie/Internal/SourceLocationProvider.cs, src/Fixie/Reports/TestAdapterReport.cs
`TestAdapterReport` in the primary `Fixie` project is responsible for attempting source location lookups, instead of `VsDiscoveryRecorder` in the `Fixie.TestAdapter` project, because the test adapter project is deprecated.
=> Move Source Location Lookup

.vscode/launch.json, src/Fixie.Console/Fixie.Console.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.csproj, src/Fixie.TestAdapter/Fixie.TestAdapter.nuspec, src/Fixie.Tests/CaseNameTests.cs, src/Fixie.Tests/Console/CommandLineTests.cs, src/Fixie.Tests/Fixie.Tests.csproj, src/Fixie.Tests/Utility.cs, src/Fixie/Fixie.csproj, src/Fixie/Internal/CaseNameBuilder.cs
This phases out deprecated target framework `net8.0`, which will not pass the end of it's own support window until November 10, 2026.
The rationale is that Fixie 5.0 is intended to be released sometime after `net10.0` is released in late 2025, marking the start of a new LTS cycle. Leaving in support for `net8.0` at that time would put us several years behind on adopting modern C# and .NET features.
This raises the "floor" for the solution from `net8.0` and `C# 12` to `net9.0` and `C# 13`.
=> Remove target framework `net8.0`
